export const LANGUAGES = [
  "French", "German", "Spanish", "Italian", "Portuguese", "Dutch", "Swedish", "Danish", "Finnish", "Polish", "Czech", "Slovak", "Hungarian", "Romanian", "Bulgarian", "Greek", "Slovenian", "Croatian", "Serbian", "Bosnian", "Macedonian", "Albanian", "Estonian", "Latvian", "Lithuanian", "Icelandic", "Irish", "Maltese", "Russian", "Ukrainian", "Belarusian", "Georgian", "Armenian", "Azerbaijani", "Kazakh", "Turkish", "Hebrew", "Arabic", "Japanese", "Korean", "Chinese (Simplified)", "Chinese (Traditional)", "Vietnamese", "Thai", "Indonesian", "Malay", "Hindi", "Bangla", "Urdu", "Filipino", "Tamil", "Punjabi", "Telugu", "Marathi", "Persian", "Javanese", "Kannada", "Gujarati", "Pashto", "Swahili", "Hausa", "Burmese", "Malayalam", "Sundanese", "Nepali", "Sinhala", "Khmer", "Uzbek", "Kurdish", "Yoruba", "Igbo", "Amharic", "Somali", "Lingala", "Malagasy", "Kinyarwanda", "Tajik", "Kyrgyz", "Turkmen", "Mongolian", "Lao", "Tibetan", "Norwegian", "Catalan", "Afrikaans", "Zulu", "Xhosa", "Wolof", "Fula", "Bambara", "Shona", "Tswana", "Southern Sotho", "Tsonga", "Tigrinya", "Odia", "Assamese", "Sindhi", "Uyghur", "Tatar", "Basque", "Welsh", "Scottish Gaelic", "Occitan", "Māori", "Samoan", "Tongan", "Hawaiian", "Rundi", "Swati", "Venda", "Kamba", "Luo", "Ganda", "Haitian Creole", "Luxembourgish", "Breton", "Faroese", "Guarani", "Romansh"
];

export const REGIONS: Record<string, string[]> = {
  "Europe": ["French", "German", "Spanish", "Italian", "Portuguese", "Dutch", "Swedish", "Danish", "Finnish", "Polish", "Czech", "Slovak", "Hungarian", "Romanian", "Bulgarian", "Greek", "Slovenian", "Croatian", "Serbian", "Bosnian", "Macedonian", "Albanian", "Estonian", "Latvian", "Lithuanian", "Icelandic", "Irish", "Maltese", "Russian", "Ukrainian", "Belarusian", "Norwegian", "Catalan", "Basque", "Welsh", "Scottish Gaelic", "Occitan", "Luxembourgish", "Breton", "Faroese", "Romansh"],
  "Asia": ["Georgian", "Armenian", "Azerbaijani", "Kazakh", "Turkish", "Japanese", "Korean", "Chinese (Simplified)", "Chinese (Traditional)", "Vietnamese", "Thai", "Indonesian", "Malay", "Hindi", "Bangla", "Urdu", "Filipino", "Tamil", "Punjabi", "Telugu", "Marathi", "Persian", "Javanese", "Kannada", "Gujarati", "Pashto", "Burmese", "Malayalam", "Sundanese", "Nepali", "Sinhala", "Khmer", "Uzbek", "Kurdish", "Tajik", "Kyrgyz", "Turkmen", "Mongolian", "Lao", "Tibetan", "Odia", "Assamese", "Sindhi", "Uyghur", "Tatar"],
  "Middle East & Africa": ["Hebrew", "Arabic", "Swahili", "Hausa", "Yoruba", "Igbo", "Amharic", "Somali", "Lingala", "Malagasy", "Kinyarwanda", "Afrikaans", "Zulu", "Xhosa", "Wolof", "Fula", "Bambara", "Shona", "Tswana", "Southern Sotho", "Tsonga", "Tigrinya", "Rundi", "Swati", "Venda", "Kamba", "Luo", "Ganda"],
  "Oceania": ["Māori", "Samoan", "Tongan", "Hawaiian"],
  "Americas": ["Haitian Creole", "Guarani"]
};
